name: Run Vite Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
jobs:
  run-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npm run test
