name: Run Unit Tests, TypeScript Check, and Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install-deps:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      # - name: Install dependencies
      #   run: npm ci
  unit-tests:
    needs: install-deps
    runs-on: macos-latest
    steps:
      - name: Execute tests
        run: npm run test
  typescript-check:
    needs: install-deps
    runs-on: macos-latest
    steps:
      - name: Execute tests
        run: npm run tsc-check
  lint:
    needs: install-deps
    runs-on: macos-latest
    steps:
      - name: Execute tests
        run: npm run lint-err-only
